-- Migration: 0002_kids_expenses_schema
-- Description: Create tables for kids expenses app

CREATE TABLE IF NOT EXISTS ledgers (
	id TEXT PRIMARY KEY NOT NULL,
	name TEXT NOT NULL,
	created_at INTEGER DEFAULT (CURRENT_TIMESTAMP) NOT NULL,
	updated_at INTEGER DEFAULT (CURRENT_TIMESTAMP) NOT NULL
);

CREATE TABLE IF NOT EXISTS kids (
	id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
	ledger_id TEXT NOT NULL,
	name TEXT NOT NULL,
	emoji TEXT NOT NULL,
	created_at INTEGER DEFAULT (CURRENT_TIMESTAMP) NOT NULL,
	updated_at INTEGER DEFAULT (CURRENT_TIMESTAMP) NOT NULL,
	FOREIGN KEY (ledger_id) REFERENCES ledgers(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_kids_ledger_id ON kids(ledger_id);

CREATE TABLE IF NOT EXISTS accounts (
	id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
	kid_id INTEGER NOT NULL,
	name TEXT NOT NULL,
	balance INTEGER DEFAULT 0 NOT NULL,
	created_at INTEGER DEFAULT (CURRENT_TIMESTAMP) NOT NULL,
	updated_at INTEGER DEFAULT (CURRENT_TIMESTAMP) NOT NULL,
	FOREIGN KEY (kid_id) REFERENCES kids(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_accounts_kid_id ON accounts(kid_id);