import { post, route } from 'remix/fetch-router/routes'

export const routes = route({
	home: '/',
	about: '/about',
	chat: '/chat',
	health: '/health',
	login: '/login',
	signup: '/signup',
	resetPassword: '/reset-password',
	oauthAuthorize: '/oauth/authorize',
	oauthCallback: '/oauth/callback',
	account: '/account',
	history: '/history',
	settings: '/settings',
	privacyPolicy: '/privacy-policy',
	termsOfService: '/terms-of-service',
	auth: post('/auth'),
	session: '/session',
	logout: post('/logout'),
	passwordResetRequest: post('/password-reset'),
	passwordResetConfirm: post('/password-reset/confirm'),
	apiLedgerDashboard: '/ledger/dashboard',
	apiLedgerSettings: '/ledger/settings',
	apiLedgerHistory: '/ledger/history',
	apiKidsCreate: post('/ledger/kids/create'),
	apiKidsUpdate: post('/ledger/kids/update'),
	apiKidsReorder: post('/ledger/kids/reorder'),
	apiKidsArchive: post('/ledger/kids/archive'),
	apiKidsUnarchive: post('/ledger/kids/unarchive'),
	apiKidsDelete: post('/ledger/kids/delete'),
	apiAccountsCreate: post('/ledger/accounts/create'),
	apiAccountsUpdate: post('/ledger/accounts/update'),
	apiAccountsReorder: post('/ledger/accounts/reorder'),
	apiAccountsArchive: post('/ledger/accounts/archive'),
	apiAccountsUnarchive: post('/ledger/accounts/unarchive'),
	apiAccountsDelete: post('/ledger/accounts/delete'),
	apiTransactionsCreate: post('/ledger/transactions/create'),
	apiQuickAmountsSet: post('/ledger/quick-amounts/set'),
	apiExportJson: '/ledger/export/json',
})
